theme: jekyll-theme-midnight
title: Friends of Colden CLough
description: A friendly community volunteer group carrying out nature restoration work in the ancient woodland of Colden Clough
markdown: kramdown
plugins:
- jekyll-remote-theme