name: update-site
on:
  schedule:
    - cron: '10 5 * * *'
jobs:
  update-opening:
    runs-on: ubuntu-latest
    name: Run daily build to ensure events listings are kept up to date 
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Update and commit
        run: | 
          cd main
          git config --global user.name 'bjorsq'
          git config --global user.email 'pete@bjorsq.net'
          git commit --allow-empty -am "[bot] daily build to ensure events listings are kept up to date" && git push
